// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef _XGP_V3_UI_H
#define _XGP_V3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Boot.h"
#include "screens/ui_Splash.h"
#include "screens/ui_SystemInfo.h"
#include "screens/ui_SystemStatus.h"
#include "screens/ui_NetworkInfo.h"
#include "screens/ui_ModemInfo.h"
#include "screens/ui_ModemSignal.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * fadein_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fadeinfromleft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fadeinfromright_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_581822748);    // assets/hdimg-120-big-light.png

// FONTS
LV_FONT_DECLARE(ui_font_MiSans20);
LV_FONT_DECLARE(ui_font_MiSans24);
LV_FONT_DECLARE(ui_font_MiSans16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
