// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_Boot = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions
void ui_event_Boot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Splash, LV_SCR_LOAD_ANIM_FADE_ON, 300, 1000, &ui_Splash_screen_init);
        fadein_Animation(ui_Spinner1, 0);
    }
}

// build funtions

void ui_Boot_screen_init(void)
{
    ui_Boot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Boot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Boot);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_decoration);
    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_decoration);

    lv_obj_add_event_cb(ui_Boot, ui_event_Boot, LV_EVENT_ALL, NULL);

}

void ui_Boot_screen_destroy(void)
{
    if(ui_Boot) lv_obj_del(ui_Boot);

    // NULL screen variables
    ui_Boot = NULL;
    ui_Spinner1 = NULL;

}
