// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Boot
extern void ui_Boot_screen_init(void);
extern void ui_Boot_screen_destroy(void);
extern void ui_event_Boot(lv_event_t * e);
extern lv_obj_t * ui_Boot;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

