// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_ModemSignal = NULL;
lv_obj_t * ui_headerModemSignal = NULL;
lv_obj_t * ui_txtModemSignal = NULL;
lv_obj_t * ui_txtModemSignal1 = NULL;
lv_obj_t * ui_valModemSignalName1 = NULL;
lv_obj_t * ui_valModemSignalValue1 = NULL;
lv_obj_t * ui_valModemSignalBar1 = NULL;
lv_obj_t * ui_valModemSignalName2 = NULL;
lv_obj_t * ui_valModemSignalValue2 = NULL;
lv_obj_t * ui_valModemSignalBar2 = NULL;
lv_obj_t * ui_valModemSignalName3 = NULL;
lv_obj_t * ui_valModemSignalValue3 = NULL;
lv_obj_t * ui_valModemSignalBar3 = NULL;
// event funtions
void ui_event_ModemSignal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_SystemInfo, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 5000, &ui_SystemInfo_screen_init);
    }
}

// build funtions

void ui_ModemSignal_screen_init(void)
{
    ui_ModemSignal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ModemSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerModemSignal = lv_obj_create(ui_ModemSignal);
    lv_obj_set_width(ui_headerModemSignal, 320);
    lv_obj_set_height(ui_headerModemSignal, 30);
    lv_obj_set_x(ui_headerModemSignal, 0);
    lv_obj_set_y(ui_headerModemSignal, -70);
    lv_obj_set_align(ui_headerModemSignal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_headerModemSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtModemSignal = lv_label_create(ui_headerModemSignal);
    lv_obj_set_width(ui_txtModemSignal, lv_pct(100));
    lv_obj_set_height(ui_txtModemSignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtModemSignal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemSignal, "调制解调器信号");
    ui_object_set_themeable_style_property(ui_txtModemSignal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtModemSignal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtModemSignal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemSignal, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemSignal1 = lv_label_create(ui_headerModemSignal);
    lv_obj_set_width(ui_txtModemSignal1, lv_pct(100));
    lv_obj_set_height(ui_txtModemSignal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtModemSignal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemSignal1, "(5/5)");
    ui_object_set_themeable_style_property(ui_txtModemSignal1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtModemSignal1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtModemSignal1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemSignal1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalName1 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalName1, 60);
    lv_obj_set_height(ui_valModemSignalName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalName1, -110);
    lv_obj_set_y(ui_valModemSignalName1, -30);
    lv_obj_set_align(ui_valModemSignalName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalName1, "RSRQ");
    lv_obj_set_style_text_align(ui_valModemSignalName1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalName1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalValue1 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalValue1, 220);
    lv_obj_set_height(ui_valModemSignalValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalValue1, 30);
    lv_obj_set_y(ui_valModemSignalValue1, -30);
    lv_obj_set_align(ui_valModemSignalValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalValue1, "-108/-44dbm");
    lv_obj_set_style_text_align(ui_valModemSignalValue1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalValue1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalBar1 = lv_bar_create(ui_ModemSignal);
    lv_bar_set_range(ui_valModemSignalBar1, -140, -44);
    lv_bar_set_value(ui_valModemSignalBar1, -100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_valModemSignalBar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_valModemSignalBar1, 280);
    lv_obj_set_height(ui_valModemSignalBar1, 10);
    lv_obj_set_x(ui_valModemSignalBar1, 0);
    lv_obj_set_y(ui_valModemSignalBar1, -15);
    lv_obj_set_align(ui_valModemSignalBar1, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_valModemSignalBar1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_decoration);
    ui_object_set_themeable_style_property(ui_valModemSignalBar1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_decoration);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_valModemSignalBar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_valModemSignalBar1,
                                                                                                         lv_obj_get_style_pad_right(ui_valModemSignalBar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_valModemSignalName2 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalName2, 60);
    lv_obj_set_height(ui_valModemSignalName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalName2, -110);
    lv_obj_set_y(ui_valModemSignalName2, 10);
    lv_obj_set_align(ui_valModemSignalName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalName2, "RSRP");
    lv_obj_set_style_text_align(ui_valModemSignalName2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalName2, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalValue2 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalValue2, 220);
    lv_obj_set_height(ui_valModemSignalValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalValue2, 30);
    lv_obj_set_y(ui_valModemSignalValue2, 10);
    lv_obj_set_align(ui_valModemSignalValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalValue2, "-108/-44dbm");
    lv_obj_set_style_text_align(ui_valModemSignalValue2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalValue2, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalBar2 = lv_bar_create(ui_ModemSignal);
    lv_bar_set_range(ui_valModemSignalBar2, -19, -3);
    lv_bar_set_value(ui_valModemSignalBar2, -13, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_valModemSignalBar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_valModemSignalBar2, 280);
    lv_obj_set_height(ui_valModemSignalBar2, 10);
    lv_obj_set_x(ui_valModemSignalBar2, 0);
    lv_obj_set_y(ui_valModemSignalBar2, 25);
    lv_obj_set_align(ui_valModemSignalBar2, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_valModemSignalBar2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_decoration);
    ui_object_set_themeable_style_property(ui_valModemSignalBar2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_decoration);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_valModemSignalBar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_valModemSignalBar2,
                                                                                                         lv_obj_get_style_pad_right(ui_valModemSignalBar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_valModemSignalName3 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalName3, 60);
    lv_obj_set_height(ui_valModemSignalName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalName3, -110);
    lv_obj_set_y(ui_valModemSignalName3, 50);
    lv_obj_set_align(ui_valModemSignalName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalName3, "SINR");
    lv_obj_set_style_text_align(ui_valModemSignalName3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalName3, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalValue3 = lv_label_create(ui_ModemSignal);
    lv_obj_set_width(ui_valModemSignalValue3, 220);
    lv_obj_set_height(ui_valModemSignalValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemSignalValue3, 30);
    lv_obj_set_y(ui_valModemSignalValue3, 50);
    lv_obj_set_align(ui_valModemSignalValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemSignalValue3, "-108/-44dbm");
    lv_obj_set_style_text_align(ui_valModemSignalValue3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemSignalValue3, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemSignalBar3 = lv_bar_create(ui_ModemSignal);
    lv_bar_set_value(ui_valModemSignalBar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_valModemSignalBar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_valModemSignalBar3, 280);
    lv_obj_set_height(ui_valModemSignalBar3, 10);
    lv_obj_set_x(ui_valModemSignalBar3, 0);
    lv_obj_set_y(ui_valModemSignalBar3, 65);
    lv_obj_set_align(ui_valModemSignalBar3, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_valModemSignalBar3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_decoration);
    ui_object_set_themeable_style_property(ui_valModemSignalBar3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_decoration);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_valModemSignalBar3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_valModemSignalBar3,
                                                                                                         lv_obj_get_style_pad_right(ui_valModemSignalBar3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_ModemSignal, ui_event_ModemSignal, LV_EVENT_ALL, NULL);

}

void ui_ModemSignal_screen_destroy(void)
{
    if(ui_ModemSignal) lv_obj_del(ui_ModemSignal);

    // NULL screen variables
    ui_ModemSignal = NULL;
    ui_headerModemSignal = NULL;
    ui_txtModemSignal = NULL;
    ui_txtModemSignal1 = NULL;
    ui_valModemSignalName1 = NULL;
    ui_valModemSignalValue1 = NULL;
    ui_valModemSignalBar1 = NULL;
    ui_valModemSignalName2 = NULL;
    ui_valModemSignalValue2 = NULL;
    ui_valModemSignalBar2 = NULL;
    ui_valModemSignalName3 = NULL;
    ui_valModemSignalValue3 = NULL;
    ui_valModemSignalBar3 = NULL;

}
