// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * uic_valModemRev;
lv_obj_t * ui_ModemInfo = NULL;
lv_obj_t * ui_headerModemInfo = NULL;
lv_obj_t * ui_txtModemInfo = NULL;
lv_obj_t * ui_txtModemInfo1 = NULL;
lv_obj_t * ui_txtModemRev = NULL;
lv_obj_t * ui_valModemRev = NULL;
lv_obj_t * ui_txtModemTempature = NULL;
lv_obj_t * ui_valModemTempature = NULL;
lv_obj_t * ui_txtModemVoltage = NULL;
lv_obj_t * ui_valModemVoltage = NULL;
lv_obj_t * ui_txtModemISP = NULL;
lv_obj_t * ui_valModemISP = NULL;
lv_obj_t * ui_txtModemNetworkType = NULL;
lv_obj_t * ui_valModemNetworkType = NULL;
lv_obj_t * ui_txtModemCQI = NULL;
lv_obj_t * ui_valModemCQI = NULL;
lv_obj_t * ui_txtModemAmbr = NULL;
lv_obj_t * ui_valModemAmbr = NULL;
// event funtions
void ui_event_ModemInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ModemSignal, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 5000, &ui_ModemSignal_screen_init);
    }
}

// build funtions

void ui_ModemInfo_screen_init(void)
{
    ui_ModemInfo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ModemInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerModemInfo = lv_obj_create(ui_ModemInfo);
    lv_obj_set_width(ui_headerModemInfo, 320);
    lv_obj_set_height(ui_headerModemInfo, 30);
    lv_obj_set_x(ui_headerModemInfo, 0);
    lv_obj_set_y(ui_headerModemInfo, -70);
    lv_obj_set_align(ui_headerModemInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_headerModemInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtModemInfo = lv_label_create(ui_headerModemInfo);
    lv_obj_set_width(ui_txtModemInfo, lv_pct(100));
    lv_obj_set_height(ui_txtModemInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtModemInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemInfo, "调制解调器信息");
    ui_object_set_themeable_style_property(ui_txtModemInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtModemInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtModemInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemInfo, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemInfo1 = lv_label_create(ui_headerModemInfo);
    lv_obj_set_width(ui_txtModemInfo1, lv_pct(100));
    lv_obj_set_height(ui_txtModemInfo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtModemInfo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemInfo1, "(4/5)");
    ui_object_set_themeable_style_property(ui_txtModemInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtModemInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtModemInfo1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemInfo1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemRev = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemRev, 50);
    lv_obj_set_height(ui_txtModemRev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemRev, -120);
    lv_obj_set_y(ui_txtModemRev, -30);
    lv_obj_set_align(ui_txtModemRev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemRev, "Rev: ");
    lv_obj_set_style_text_align(ui_txtModemRev, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemRev, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemRev = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemRev, 250);
    lv_obj_set_height(ui_valModemRev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemRev, 30);
    lv_obj_set_y(ui_valModemRev, -30);
    lv_obj_set_align(ui_valModemRev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemRev, "RM500QGLABR13XXXXXX");
    lv_obj_set_style_text_align(ui_valModemRev, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemRev, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemTempature = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemTempature, 50);
    lv_obj_set_height(ui_txtModemTempature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemTempature, -120);
    lv_obj_set_y(ui_txtModemTempature, 0);
    lv_obj_set_align(ui_txtModemTempature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemTempature, "温度: ");
    lv_obj_set_style_text_align(ui_txtModemTempature, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemTempature, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemTempature = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemTempature, 90);
    lv_obj_set_height(ui_valModemTempature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemTempature, -50);
    lv_obj_set_y(ui_valModemTempature, 0);
    lv_obj_set_align(ui_valModemTempature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemTempature, "00.00℃");
    lv_obj_set_style_text_align(ui_valModemTempature, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemTempature, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemVoltage = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemVoltage, 50);
    lv_obj_set_height(ui_txtModemVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemVoltage, 25);
    lv_obj_set_y(ui_txtModemVoltage, 0);
    lv_obj_set_align(ui_txtModemVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemVoltage, "电压: ");
    lv_obj_set_style_text_align(ui_txtModemVoltage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemVoltage, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemVoltage = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemVoltage, 90);
    lv_obj_set_height(ui_valModemVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemVoltage, 95);
    lv_obj_set_y(ui_valModemVoltage, 0);
    lv_obj_set_align(ui_valModemVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemVoltage, "0000 mV");
    lv_obj_set_style_text_align(ui_valModemVoltage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemVoltage, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemISP = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemISP, 50);
    lv_obj_set_height(ui_txtModemISP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemISP, -120);
    lv_obj_set_y(ui_txtModemISP, 30);
    lv_obj_set_align(ui_txtModemISP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemISP, "ISP: ");
    lv_obj_set_style_text_align(ui_txtModemISP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemISP, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemISP = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemISP, 90);
    lv_obj_set_height(ui_valModemISP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemISP, -50);
    lv_obj_set_y(ui_valModemISP, 30);
    lv_obj_set_align(ui_valModemISP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemISP, "中国铁通");
    lv_obj_set_style_text_align(ui_valModemISP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemISP, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemNetworkType = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemNetworkType, 50);
    lv_obj_set_height(ui_txtModemNetworkType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemNetworkType, 25);
    lv_obj_set_y(ui_txtModemNetworkType, 30);
    lv_obj_set_align(ui_txtModemNetworkType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemNetworkType, "类型: ");
    lv_obj_set_style_text_align(ui_txtModemNetworkType, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemNetworkType, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemNetworkType = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemNetworkType, 90);
    lv_obj_set_height(ui_valModemNetworkType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemNetworkType, 95);
    lv_obj_set_y(ui_valModemNetworkType, 30);
    lv_obj_set_align(ui_valModemNetworkType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemNetworkType, "NR6G-SA");
    lv_obj_set_style_text_align(ui_valModemNetworkType, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemNetworkType, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemCQI = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemCQI, 50);
    lv_obj_set_height(ui_txtModemCQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemCQI, -120);
    lv_obj_set_y(ui_txtModemCQI, 60);
    lv_obj_set_align(ui_txtModemCQI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemCQI, "CQI: ");
    lv_obj_set_style_text_align(ui_txtModemCQI, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemCQI, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemCQI = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemCQI, 90);
    lv_obj_set_height(ui_valModemCQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemCQI, -50);
    lv_obj_set_y(ui_valModemCQI, 60);
    lv_obj_set_align(ui_valModemCQI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemCQI, "DL 5 UL 5");
    lv_obj_set_style_text_align(ui_valModemCQI, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemCQI, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemAmbr = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_txtModemAmbr, 50);
    lv_obj_set_height(ui_txtModemAmbr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemAmbr, 25);
    lv_obj_set_y(ui_txtModemAmbr, 60);
    lv_obj_set_align(ui_txtModemAmbr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemAmbr, "协商: ");
    lv_obj_set_style_text_align(ui_txtModemAmbr, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemAmbr, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemAmbr = lv_label_create(ui_ModemInfo);
    lv_obj_set_width(ui_valModemAmbr, 90);
    lv_obj_set_height(ui_valModemAmbr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemAmbr, 95);
    lv_obj_set_y(ui_valModemAmbr, 60);
    lv_obj_set_align(ui_valModemAmbr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemAmbr, "9999/8888");
    lv_obj_set_style_text_align(ui_valModemAmbr, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valModemAmbr, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ModemInfo, ui_event_ModemInfo, LV_EVENT_ALL, NULL);
    uic_valModemRev = ui_valModemRev;

}

void ui_ModemInfo_screen_destroy(void)
{
    if(ui_ModemInfo) lv_obj_del(ui_ModemInfo);

    // NULL screen variables
    ui_ModemInfo = NULL;
    ui_headerModemInfo = NULL;
    ui_txtModemInfo = NULL;
    ui_txtModemInfo1 = NULL;
    ui_txtModemRev = NULL;
    uic_valModemRev = NULL;
    ui_valModemRev = NULL;
    ui_txtModemTempature = NULL;
    ui_valModemTempature = NULL;
    ui_txtModemVoltage = NULL;
    ui_valModemVoltage = NULL;
    ui_txtModemISP = NULL;
    ui_valModemISP = NULL;
    ui_txtModemNetworkType = NULL;
    ui_valModemNetworkType = NULL;
    ui_txtModemCQI = NULL;
    ui_valModemCQI = NULL;
    ui_txtModemAmbr = NULL;
    ui_valModemAmbr = NULL;

}
