// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_MODEMINFO_H
#define UI_MODEMINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ModemInfo
extern void ui_ModemInfo_screen_init(void);
extern void ui_ModemInfo_screen_destroy(void);
extern void ui_event_ModemInfo(lv_event_t * e);
extern lv_obj_t * ui_ModemInfo;
extern lv_obj_t * ui_headerModemInfo;
extern lv_obj_t * ui_txtModemInfo;
extern lv_obj_t * ui_txtModemInfo1;
extern lv_obj_t * ui_txtModemRev;
extern lv_obj_t * ui_valModemRev;
extern lv_obj_t * ui_txtModemTempature;
extern lv_obj_t * ui_valModemTempature;
extern lv_obj_t * ui_txtModemVoltage;
extern lv_obj_t * ui_valModemVoltage;
extern lv_obj_t * ui_txtModemISP;
extern lv_obj_t * ui_valModemISP;
extern lv_obj_t * ui_txtModemNetworkType;
extern lv_obj_t * ui_valModemNetworkType;
extern lv_obj_t * ui_txtModemCQI;
extern lv_obj_t * ui_valModemCQI;
extern lv_obj_t * ui_txtModemAmbr;
extern lv_obj_t * ui_valModemAmbr;
// CUSTOM VARIABLES
extern lv_obj_t * uic_valModemRev;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

