// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_MODEMSIGNAL_H
#define UI_MODEMSIGNAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ModemSignal
extern void ui_ModemSignal_screen_init(void);
extern void ui_ModemSignal_screen_destroy(void);
extern void ui_event_ModemSignal(lv_event_t * e);
extern lv_obj_t * ui_ModemSignal;
extern lv_obj_t * ui_headerModemSignal;
extern lv_obj_t * ui_txtModemSignal;
extern lv_obj_t * ui_txtModemSignal1;
extern lv_obj_t * ui_valModemSignalName1;
extern lv_obj_t * ui_valModemSignalValue1;
extern lv_obj_t * ui_valModemSignalBar1;
extern lv_obj_t * ui_valModemSignalName2;
extern lv_obj_t * ui_valModemSignalValue2;
extern lv_obj_t * ui_valModemSignalBar2;
extern lv_obj_t * ui_valModemSignalName3;
extern lv_obj_t * ui_valModemSignalValue3;
extern lv_obj_t * ui_valModemSignalBar3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

