// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_NETWORKINFO_H
#define UI_NETWORKINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NetworkInfo
extern void ui_NetworkInfo_screen_init(void);
extern void ui_NetworkInfo_screen_destroy(void);
extern void ui_event_NetworkInfo(lv_event_t * e);
extern lv_obj_t * ui_NetworkInfo;
extern lv_obj_t * ui_headerNetworkInfo;
extern lv_obj_t * ui_txtNetworkInfo;
extern lv_obj_t * ui_txtNetworkInfo1;
extern lv_obj_t * ui_txtModemIp;
extern lv_obj_t * ui_valModemIp;
extern lv_obj_t * ui_txtWanIp;
extern lv_obj_t * ui_valWanIp;
extern lv_obj_t * ui_txtLanIp;
extern lv_obj_t * ui_valLanIp;
extern lv_obj_t * ui_txtActiveConnect;
extern lv_obj_t * ui_valActiveConnect;
extern lv_obj_t * ui_txtArpCount;
extern lv_obj_t * ui_valArpCount;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

