// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_NetworkInfo = NULL;
lv_obj_t * ui_headerNetworkInfo = NULL;
lv_obj_t * ui_txtNetworkInfo = NULL;
lv_obj_t * ui_txtNetworkInfo1 = NULL;
lv_obj_t * ui_txtModemIp = NULL;
lv_obj_t * ui_valModemIp = NULL;
lv_obj_t * ui_txtWanIp = NULL;
lv_obj_t * ui_valWanIp = NULL;
lv_obj_t * ui_txtLanIp = NULL;
lv_obj_t * ui_valLanIp = NULL;
lv_obj_t * ui_txtActiveConnect = NULL;
lv_obj_t * ui_valActiveConnect = NULL;
lv_obj_t * ui_txtArpCount = NULL;
lv_obj_t * ui_valArpCount = NULL;
// event funtions
void ui_event_NetworkInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ModemInfo, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 5000, &ui_ModemInfo_screen_init);
    }
}

// build funtions

void ui_NetworkInfo_screen_init(void)
{
    ui_NetworkInfo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NetworkInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerNetworkInfo = lv_obj_create(ui_NetworkInfo);
    lv_obj_set_width(ui_headerNetworkInfo, 320);
    lv_obj_set_height(ui_headerNetworkInfo, 30);
    lv_obj_set_x(ui_headerNetworkInfo, 0);
    lv_obj_set_y(ui_headerNetworkInfo, -70);
    lv_obj_set_align(ui_headerNetworkInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_headerNetworkInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtNetworkInfo = lv_label_create(ui_headerNetworkInfo);
    lv_obj_set_width(ui_txtNetworkInfo, lv_pct(100));
    lv_obj_set_height(ui_txtNetworkInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtNetworkInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtNetworkInfo, "网络信息");
    ui_object_set_themeable_style_property(ui_txtNetworkInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtNetworkInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtNetworkInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtNetworkInfo, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtNetworkInfo1 = lv_label_create(ui_headerNetworkInfo);
    lv_obj_set_width(ui_txtNetworkInfo1, lv_pct(100));
    lv_obj_set_height(ui_txtNetworkInfo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtNetworkInfo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtNetworkInfo1, "(3/5)");
    ui_object_set_themeable_style_property(ui_txtNetworkInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtNetworkInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtNetworkInfo1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtNetworkInfo1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtModemIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_txtModemIp, 100);
    lv_obj_set_height(ui_txtModemIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtModemIp, -100);
    lv_obj_set_y(ui_txtModemIp, -30);
    lv_obj_set_align(ui_txtModemIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtModemIp, "Modem IP: ");
    lv_obj_set_style_text_align(ui_txtModemIp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtModemIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valModemIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_valModemIp, 200);
    lv_obj_set_height(ui_valModemIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valModemIp, 50);
    lv_obj_set_y(ui_valModemIp, -30);
    lv_obj_set_align(ui_valModemIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valModemIp, "203.0.113.123");
    lv_obj_set_style_text_font(ui_valModemIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtWanIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_txtWanIp, 100);
    lv_obj_set_height(ui_txtWanIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtWanIp, -100);
    lv_obj_set_y(ui_txtWanIp, 0);
    lv_obj_set_align(ui_txtWanIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtWanIp, "WAN IP: ");
    lv_obj_set_style_text_align(ui_txtWanIp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtWanIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valWanIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_valWanIp, 200);
    lv_obj_set_height(ui_valWanIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valWanIp, 50);
    lv_obj_set_y(ui_valWanIp, 0);
    lv_obj_set_align(ui_valWanIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valWanIp, "198.51.100.233");
    lv_obj_set_style_text_font(ui_valWanIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtLanIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_txtLanIp, 100);
    lv_obj_set_height(ui_txtLanIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtLanIp, -100);
    lv_obj_set_y(ui_txtLanIp, 30);
    lv_obj_set_align(ui_txtLanIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtLanIp, "LAN IP: ");
    lv_obj_set_style_text_align(ui_txtLanIp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtLanIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valLanIp = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_valLanIp, 200);
    lv_obj_set_height(ui_valLanIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valLanIp, 50);
    lv_obj_set_y(ui_valLanIp, 30);
    lv_obj_set_align(ui_valLanIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valLanIp, "192.0.2.1");
    lv_obj_set_style_text_font(ui_valLanIp, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtActiveConnect = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_txtActiveConnect, 100);
    lv_obj_set_height(ui_txtActiveConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtActiveConnect, -100);
    lv_obj_set_y(ui_txtActiveConnect, 60);
    lv_obj_set_align(ui_txtActiveConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtActiveConnect, "活动连接数: ");
    lv_obj_set_style_text_align(ui_txtActiveConnect, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtActiveConnect, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valActiveConnect = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_valActiveConnect, 60);
    lv_obj_set_height(ui_valActiveConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valActiveConnect, -20);
    lv_obj_set_y(ui_valActiveConnect, 60);
    lv_obj_set_align(ui_valActiveConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valActiveConnect, "65535");
    lv_obj_set_style_text_align(ui_valActiveConnect, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valActiveConnect, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtArpCount = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_txtArpCount, 80);
    lv_obj_set_height(ui_txtArpCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtArpCount, 60);
    lv_obj_set_y(ui_txtArpCount, 60);
    lv_obj_set_align(ui_txtArpCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtArpCount, "在线设备: ");
    lv_obj_set_style_text_align(ui_txtArpCount, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtArpCount, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valArpCount = lv_label_create(ui_NetworkInfo);
    lv_obj_set_width(ui_valArpCount, 200);
    lv_obj_set_height(ui_valArpCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valArpCount, 200);
    lv_obj_set_y(ui_valArpCount, 60);
    lv_obj_set_align(ui_valArpCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valArpCount, "233");
    lv_obj_set_style_text_font(ui_valArpCount, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_NetworkInfo, ui_event_NetworkInfo, LV_EVENT_ALL, NULL);

}

void ui_NetworkInfo_screen_destroy(void)
{
    if(ui_NetworkInfo) lv_obj_del(ui_NetworkInfo);

    // NULL screen variables
    ui_NetworkInfo = NULL;
    ui_headerNetworkInfo = NULL;
    ui_txtNetworkInfo = NULL;
    ui_txtNetworkInfo1 = NULL;
    ui_txtModemIp = NULL;
    ui_valModemIp = NULL;
    ui_txtWanIp = NULL;
    ui_valWanIp = NULL;
    ui_txtLanIp = NULL;
    ui_valLanIp = NULL;
    ui_txtActiveConnect = NULL;
    ui_valActiveConnect = NULL;
    ui_txtArpCount = NULL;
    ui_valArpCount = NULL;

}
