// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Splash_hdimg = NULL;
lv_obj_t * ui_Prodcut_Name = NULL;
lv_obj_t * ui_Product_Name_English = NULL;
lv_obj_t * ui_Author = NULL;
// event funtions
void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fadeinfromleft_Animation(ui_Splash_hdimg, 0);
        fadeinfromright_Animation(ui_Author, 0);
        fadeinfromright_Animation(ui_Product_Name_English, 0);
        fadeinfromright_Animation(ui_Prodcut_Name, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_SystemInfo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 5000, &ui_SystemInfo_screen_init);
    }
}

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_hdimg = lv_image_create(ui_Splash);
    lv_image_set_src(ui_Splash_hdimg, &ui_img_581822748);
    lv_obj_set_width(ui_Splash_hdimg, 300);
    lv_obj_set_height(ui_Splash_hdimg, 120);
    lv_obj_set_align(ui_Splash_hdimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Splash_hdimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Splash_hdimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Splash_hdimg, LV_IMAGE_ALIGN_LEFT_MID);

    ui_Prodcut_Name = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Prodcut_Name, 150);
    lv_obj_set_height(ui_Prodcut_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Prodcut_Name, 60);
    lv_obj_set_y(ui_Prodcut_Name, -25);
    lv_obj_set_align(ui_Prodcut_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Prodcut_Name, "西瓜皮 V3");
    lv_obj_set_style_text_color(ui_Prodcut_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Prodcut_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Prodcut_Name, &ui_font_MiSans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Product_Name_English = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Product_Name_English, 150);
    lv_obj_set_height(ui_Product_Name_English, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Product_Name_English, 60);
    lv_obj_set_y(ui_Product_Name_English, 0);
    lv_obj_set_align(ui_Product_Name_English, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Product_Name_English, "NLnet XiGuaPi Board V3");
    ui_object_set_themeable_style_property(ui_Product_Name_English, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_decoration);
    ui_object_set_themeable_style_property(ui_Product_Name_English, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_decoration);
    lv_obj_set_style_text_font(ui_Product_Name_English, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Author = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Author, 150);
    lv_obj_set_height(ui_Author, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Author, 60);
    lv_obj_set_y(ui_Author, 25);
    lv_obj_set_align(ui_Author, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Author, "GitHub @zzzz0317");
    lv_obj_set_style_text_color(ui_Author, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Author, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_Splash_hdimg = NULL;
    ui_Prodcut_Name = NULL;
    ui_Product_Name_English = NULL;
    ui_Author = NULL;

}
