// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_SystemInfo = NULL;
lv_obj_t * ui_headerSystemInfo = NULL;
lv_obj_t * ui_txtSystemInfo = NULL;
lv_obj_t * ui_txtSystemInfo1 = NULL;
lv_obj_t * ui_txtHostname = NULL;
lv_obj_t * ui_valHostname = NULL;
lv_obj_t * ui_txtSysVersion = NULL;
lv_obj_t * ui_valSysVersion = NULL;
lv_obj_t * ui_txtBuildId = NULL;
lv_obj_t * ui_valBuildId = NULL;
lv_obj_t * ui_txtKernelVersion = NULL;
lv_obj_t * ui_valKernelVersion = NULL;
// event funtions
void ui_event_SystemInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_SystemStatus, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 5000, &ui_SystemStatus_screen_init);
    }
}

// build funtions

void ui_SystemInfo_screen_init(void)
{
    ui_SystemInfo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SystemInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerSystemInfo = lv_obj_create(ui_SystemInfo);
    lv_obj_set_width(ui_headerSystemInfo, 320);
    lv_obj_set_height(ui_headerSystemInfo, 30);
    lv_obj_set_x(ui_headerSystemInfo, 0);
    lv_obj_set_y(ui_headerSystemInfo, -70);
    lv_obj_set_align(ui_headerSystemInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_headerSystemInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtSystemInfo = lv_label_create(ui_headerSystemInfo);
    lv_obj_set_width(ui_txtSystemInfo, lv_pct(100));
    lv_obj_set_height(ui_txtSystemInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtSystemInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtSystemInfo, "系统信息");
    ui_object_set_themeable_style_property(ui_txtSystemInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtSystemInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtSystemInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSystemInfo, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSystemInfo1 = lv_label_create(ui_headerSystemInfo);
    lv_obj_set_width(ui_txtSystemInfo1, lv_pct(100));
    lv_obj_set_height(ui_txtSystemInfo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtSystemInfo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtSystemInfo1, "(1/5)");
    ui_object_set_themeable_style_property(ui_txtSystemInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtSystemInfo1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtSystemInfo1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSystemInfo1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtHostname = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_txtHostname, 100);
    lv_obj_set_height(ui_txtHostname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtHostname, -100);
    lv_obj_set_y(ui_txtHostname, -30);
    lv_obj_set_align(ui_txtHostname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtHostname, "主机名称: ");
    lv_obj_set_style_text_align(ui_txtHostname, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtHostname, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valHostname = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_valHostname, 200);
    lv_obj_set_height(ui_valHostname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valHostname, 50);
    lv_obj_set_y(ui_valHostname, -30);
    lv_obj_set_align(ui_valHostname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valHostname, "zzXGP");
    lv_obj_set_style_text_font(ui_valHostname, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSysVersion = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_txtSysVersion, 100);
    lv_obj_set_height(ui_txtSysVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtSysVersion, -100);
    lv_obj_set_y(ui_txtSysVersion, 0);
    lv_obj_set_align(ui_txtSysVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtSysVersion, "系统名称: ");
    lv_obj_set_style_text_align(ui_txtSysVersion, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSysVersion, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valSysVersion = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_valSysVersion, 200);
    lv_obj_set_height(ui_valSysVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valSysVersion, 50);
    lv_obj_set_y(ui_valSysVersion, 0);
    lv_obj_set_align(ui_valSysVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valSysVersion, "OpenWrt ?");
    lv_obj_set_style_text_font(ui_valSysVersion, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtBuildId = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_txtBuildId, 100);
    lv_obj_set_height(ui_txtBuildId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtBuildId, -100);
    lv_obj_set_y(ui_txtBuildId, 30);
    lv_obj_set_align(ui_txtBuildId, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtBuildId, "系统版本: ");
    lv_obj_set_style_text_align(ui_txtBuildId, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtBuildId, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valBuildId = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_valBuildId, 200);
    lv_obj_set_height(ui_valBuildId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valBuildId, 50);
    lv_obj_set_y(ui_valBuildId, 30);
    lv_obj_set_align(ui_valBuildId, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valBuildId, "r1234-567890abc");
    lv_obj_set_style_text_font(ui_valBuildId, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKernelVersion = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_txtKernelVersion, 100);
    lv_obj_set_height(ui_txtKernelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtKernelVersion, -100);
    lv_obj_set_y(ui_txtKernelVersion, 60);
    lv_obj_set_align(ui_txtKernelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtKernelVersion, "内核版本: ");
    lv_obj_set_style_text_align(ui_txtKernelVersion, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKernelVersion, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valKernelVersion = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_valKernelVersion, 200);
    lv_obj_set_height(ui_valKernelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valKernelVersion, 50);
    lv_obj_set_y(ui_valKernelVersion, 60);
    lv_obj_set_align(ui_valKernelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valKernelVersion, "2.33.33");
    lv_obj_set_style_text_font(ui_valKernelVersion, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SystemInfo, ui_event_SystemInfo, LV_EVENT_ALL, NULL);

}

void ui_SystemInfo_screen_destroy(void)
{
    if(ui_SystemInfo) lv_obj_del(ui_SystemInfo);

    // NULL screen variables
    ui_SystemInfo = NULL;
    ui_headerSystemInfo = NULL;
    ui_txtSystemInfo = NULL;
    ui_txtSystemInfo1 = NULL;
    ui_txtHostname = NULL;
    ui_valHostname = NULL;
    ui_txtSysVersion = NULL;
    ui_valSysVersion = NULL;
    ui_txtBuildId = NULL;
    ui_valBuildId = NULL;
    ui_txtKernelVersion = NULL;
    ui_valKernelVersion = NULL;

}
