// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Splash_hdimg;
extern lv_obj_t * ui_Prodcut_Name;
extern lv_obj_t * ui_Product_Name_English;
extern lv_obj_t * ui_Author;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

