// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_SYSTEMSTATUS_H
#define UI_SYSTEMSTATUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemStatus
extern void ui_SystemStatus_screen_init(void);
extern void ui_SystemStatus_screen_destroy(void);
extern void ui_event_SystemStatus(lv_event_t * e);
extern lv_obj_t * ui_SystemStatus;
extern lv_obj_t * ui_headerSystemStatus;
extern lv_obj_t * ui_txtSystemStatus;
extern lv_obj_t * ui_txtSystemStatus1;
extern lv_obj_t * ui_txtLoadAvg;
extern lv_obj_t * ui_valLoadAvg;
extern lv_obj_t * ui_txtMemory;
extern lv_obj_t * ui_valMemory;
extern lv_obj_t * ui_txtUptime;
extern lv_obj_t * ui_valUptime;
extern lv_obj_t * ui_txtLocalTime;
extern lv_obj_t * ui_valLocalTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

