// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#include "../ui.h"

lv_obj_t * ui_SystemStatus = NULL;
lv_obj_t * ui_headerSystemStatus = NULL;
lv_obj_t * ui_txtSystemStatus = NULL;
lv_obj_t * ui_txtSystemStatus1 = NULL;
lv_obj_t * ui_txtLoadAvg = NULL;
lv_obj_t * ui_valLoadAvg = NULL;
lv_obj_t * ui_txtMemory = NULL;
lv_obj_t * ui_valMemory = NULL;
lv_obj_t * ui_txtUptime = NULL;
lv_obj_t * ui_valUptime = NULL;
lv_obj_t * ui_txtLocalTime = NULL;
lv_obj_t * ui_valLocalTime = NULL;
// event funtions
void ui_event_SystemStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_NetworkInfo, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 5000, &ui_NetworkInfo_screen_init);
    }
}

// build funtions

void ui_SystemStatus_screen_init(void)
{
    ui_SystemStatus = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SystemStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerSystemStatus = lv_obj_create(ui_SystemStatus);
    lv_obj_set_width(ui_headerSystemStatus, 320);
    lv_obj_set_height(ui_headerSystemStatus, 30);
    lv_obj_set_x(ui_headerSystemStatus, 0);
    lv_obj_set_y(ui_headerSystemStatus, -70);
    lv_obj_set_align(ui_headerSystemStatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_headerSystemStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtSystemStatus = lv_label_create(ui_headerSystemStatus);
    lv_obj_set_width(ui_txtSystemStatus, lv_pct(100));
    lv_obj_set_height(ui_txtSystemStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtSystemStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtSystemStatus, "系统状态");
    ui_object_set_themeable_style_property(ui_txtSystemStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtSystemStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtSystemStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSystemStatus, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSystemStatus1 = lv_label_create(ui_headerSystemStatus);
    lv_obj_set_width(ui_txtSystemStatus1, lv_pct(100));
    lv_obj_set_height(ui_txtSystemStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtSystemStatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtSystemStatus1, "(2/5)");
    ui_object_set_themeable_style_property(ui_txtSystemStatus1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_txtSystemStatus1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_txtSystemStatus1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSystemStatus1, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtLoadAvg = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_txtLoadAvg, 100);
    lv_obj_set_height(ui_txtLoadAvg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtLoadAvg, -100);
    lv_obj_set_y(ui_txtLoadAvg, -30);
    lv_obj_set_align(ui_txtLoadAvg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtLoadAvg, "平均负载: ");
    lv_obj_set_style_text_align(ui_txtLoadAvg, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtLoadAvg, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valLoadAvg = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_valLoadAvg, 200);
    lv_obj_set_height(ui_valLoadAvg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valLoadAvg, 50);
    lv_obj_set_y(ui_valLoadAvg, -30);
    lv_obj_set_align(ui_valLoadAvg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valLoadAvg, "0.00 / 0.00 / 0.00");
    lv_obj_set_style_text_font(ui_valLoadAvg, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMemory = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_txtMemory, 100);
    lv_obj_set_height(ui_txtMemory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtMemory, -100);
    lv_obj_set_y(ui_txtMemory, 0);
    lv_obj_set_align(ui_txtMemory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtMemory, "内存占用: ");
    lv_obj_set_style_text_align(ui_txtMemory, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtMemory, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valMemory = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_valMemory, 200);
    lv_obj_set_height(ui_valMemory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valMemory, 50);
    lv_obj_set_y(ui_valMemory, 0);
    lv_obj_set_align(ui_valMemory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valMemory, "500.00 MB/3.84 GB(100%)");
    lv_obj_set_style_text_font(ui_valMemory, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtUptime = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_txtUptime, 100);
    lv_obj_set_height(ui_txtUptime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtUptime, -100);
    lv_obj_set_y(ui_txtUptime, 30);
    lv_obj_set_align(ui_txtUptime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtUptime, "运行时间: ");
    lv_obj_set_style_text_align(ui_txtUptime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtUptime, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valUptime = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_valUptime, 200);
    lv_obj_set_height(ui_valUptime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valUptime, 50);
    lv_obj_set_y(ui_valUptime, 30);
    lv_obj_set_align(ui_valUptime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valUptime, "150 天 14 小时 13 分 12 秒");
    lv_obj_set_style_text_font(ui_valUptime, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtLocalTime = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_txtLocalTime, 100);
    lv_obj_set_height(ui_txtLocalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtLocalTime, -100);
    lv_obj_set_y(ui_txtLocalTime, 60);
    lv_obj_set_align(ui_txtLocalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtLocalTime, "本地时间: ");
    lv_obj_set_style_text_align(ui_txtLocalTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtLocalTime, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valLocalTime = lv_label_create(ui_SystemStatus);
    lv_obj_set_width(ui_valLocalTime, 200);
    lv_obj_set_height(ui_valLocalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valLocalTime, 50);
    lv_obj_set_y(ui_valLocalTime, 60);
    lv_obj_set_align(ui_valLocalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valLocalTime, "1970-01-01 08:00:00");
    lv_obj_set_style_text_font(ui_valLocalTime, &ui_font_MiSans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SystemStatus, ui_event_SystemStatus, LV_EVENT_ALL, NULL);

}

void ui_SystemStatus_screen_destroy(void)
{
    if(ui_SystemStatus) lv_obj_del(ui_SystemStatus);

    // NULL screen variables
    ui_SystemStatus = NULL;
    ui_headerSystemStatus = NULL;
    ui_txtSystemStatus = NULL;
    ui_txtSystemStatus1 = NULL;
    ui_txtLoadAvg = NULL;
    ui_valLoadAvg = NULL;
    ui_txtMemory = NULL;
    ui_valMemory = NULL;
    ui_txtUptime = NULL;
    ui_valUptime = NULL;
    ui_txtLocalTime = NULL;
    ui_valLocalTime = NULL;

}
