// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: xgp_v3

#ifndef UI_SYSTEMINFO_H
#define UI_SYSTEMINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemInfo
extern void ui_SystemInfo_screen_init(void);
extern void ui_SystemInfo_screen_destroy(void);
extern void ui_event_SystemInfo(lv_event_t * e);
extern lv_obj_t * ui_SystemInfo;
extern lv_obj_t * ui_headerSystemInfo;
extern lv_obj_t * ui_txtSystemInfo;
extern lv_obj_t * ui_txtSystemInfo1;
extern lv_obj_t * ui_txtHostname;
extern lv_obj_t * ui_valHostname;
extern lv_obj_t * ui_txtSysVersion;
extern lv_obj_t * ui_valSysVersion;
extern lv_obj_t * ui_txtBuildId;
extern lv_obj_t * ui_valBuildId;
extern lv_obj_t * ui_txtKernelVersion;
extern lv_obj_t * ui_valKernelVersion;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

